# Generated by Django 5.2.6 on 2025-09-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_country', models.CharField(max_length=100)),
                ('destination_country', models.CharField(max_length=100)),
                ('duration', models.IntegerField(max_length=5)),
                ('price', models.IntegerField(max_length=10)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField()),
            ],
        ),
    ]
