# Generated by Django 5.2.6 on 2025-09-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.IntegerField(),
        ),
    ]
